/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.tefuna.divlife.api;

import org.junit.Test;
import jp.tefuna.divlife.api.main.Application;
import static org.junit.Assert.*;

public class ApplicationTest {
    @Test
    public void testAppHasAGreeting() {
        Application classUnderTest = new Application();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
